FROM python:3.9

RUN apt-get update && apt-get install -y cron

WORKDIR /usr/src/app
RUN rm -rf /usr/src/app
COPY requirements.txt ./
RUN pip install -r 'requirements.txt'

COPY . . 

CMD ["python", "./API.py"] 